version: '3'
services:
  trudeplo:
    build: .
    container_name: trudeplo
    ports: 
      - 5000:5000
  mock-device-ssh:
    build: ./docker/mockdevice
    # image: lscr.io/linuxserver/openssh-server:latest
    container_name: mockdevice
    hostname: mockdevice 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SUDO_ACCESS=true 
      - PASSWORD_ACCESS=true 
      - USER_PASSWORD=password 
      - USER_NAME=mockdevice 
    ports:
      - 2222:2222
    restart: unless-stopped
  
